basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: RyanTokManMokMTM@hotmaiol.com
    name: jackson.tmm
    url: https://github.com/RyanTokManMokMTM
  description: IOS Music Web Service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: music api server
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
